auth/urls.py
from django.conf.urls import url
from auth import views

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

product/urls.py
from django.conf.urls import url
from product import views

urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^(?P<uuid>[\w-]+)/detail/$',
        views.ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<shop_slug>[\w-]+)/new/$',
        views.ProductCreateView.as_view(), name='new'),
    url(r'^(?P<shop_slug>[\w-]+)/(?P<uuid>[\w-]+)/edit/$',
        views.ProductUpdateView.as_view(), name='edit'),
    url(r'^(?P<shop_slug>[\w-]+)/(?P<uuid>[\w-]+)/delete/$',
        views.ProductDeleteView.as_view(), name='delete'),
]

stores_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^', include('product.urls', namespace='product')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from djmoney.models.fields import MoneyField
from django.db import models
from django.core.validators import MinValueValidator
from shop.models import Shop
import uuid

# funcion para almacenamiento de imagenes
def content_file_name(instance, filename):
    return '/'.join(['products', str(instance.slug), filename])

# Create your models here.

class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

class Category(models.Model):
    title = models.CharField(max_length=45)
    description = models.TextField(blank=True, max_length=140)
    slug = models.SlugField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title.encode('utf-8').strip()

    def save(self, *args, **kwargs):
		if self.title:
			self.slug = slugify(self.title)
			super(Category, self).save(*args, **kwargs)
		else:
			super(Category, self).save(*args, **kwargs)

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    shop = models.ForeignKey(Shop)
    name = models.CharField(max_length=60)
    categories = models.ManyToManyField(Category)
    description = models.TextField()
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    price = MoneyField(max_digits=10, decimal_places=2, default_currency='USD')
    discount = IntegerRangeField(blank=True, null=True, min_value=0, max_value=100)
    photo = models.ImageField(upload_to=content_file_name)
    slug = models.SlugField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name.encode('utf-8').strip()

    def save(self, *args, **kwargs):
		if self.id:
			self.slug = slugify(self.name)
			super(Product, self).save(*args, **kwargs)
		else:
			super(Product, self).save(*args, **kwargs)

    def categories_text(self):
        return ', '.join([category.__str__() for category in self.categories.all()])

    def photo_url(self):
        return self.photo.url

product/forms.py
from django import forms
from product.models import Product

class ProductModelForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name','categories','description', 'quantity', 'price','discount','photo',)
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'}),
        }

product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# this project
from product.models import Product
from product.forms import ProductModelForm
from product.mixins import IsOwnerMixin
from shop.models import Shop
from review.models import Review


# Create your views here.

class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        query = self.request.GET.get('search')
        category = self.request.GET.get('category')
        fields = {'categories__slug': category}
        filter = {}
        for k, v in fields.items():
            if v:
                filter[k] = v
        # query to database
        queryset = self.model.objects.filter(**filter).order_by('-created_at')

        # if GET has query, so
        if query:
            queryset = self.filter_queryset(queryset, query)

        return queryset

    def filter_queryset(self, queryset, search):
        list_kws_str = search.lower().split()
        results = []

        for item in queryset:
            coincidence = 0
            for kw_str in list_kws_str:
                for index in range(len(item.name)):
                    if item.name.lower()[index:index+len(kw_str)] == kw_str:
                        coincidence += 1
            item.coincidence = coincidence

            if coincidence:
                results.append(item)

        results = sorted(results, key=lambda key: key.coincidence, reverse=True)
        pk_list = [pk.id for pk in results]
        clauses = ' '.join([
            "WHEN id='%s' THEN %s" % (pk, i) for i, pk in enumerate(pk_list)])
        ordering = 'CASE %s END' % clauses

        return self.model.objects.filter(pk__in=pk_list).extra(
            select={'ordering': ordering}, order_by=('ordering',))

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        for index, product in enumerate(self.object_list):
            # add discount to products
            if product.discount:
                self.object_list[index].new_price = (float(product.price)
                    - ((product.discount * float(product.price)) / 100))

            # add rating to products
            reviews = Review.objects.filter(product=product).values_list('rating', flat=True)
            if reviews:
                sum = 0
                for review in reviews:
                    sum+=int(review)
                rating = float(sum) * 5 / (5*len(reviews))
                self.object_list[index].rating = rating
        return context

class ProductDetailView(DetailView):
    model = Product
    pk_url_kwarg = 'uuid'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        # add discount
        if self.object.discount:
            self.object.new_price = (float(self.object.price)
                - ((self.object.discount * float(self.object.price)) / 100))
        # add rating
        reviews = Review.objects.filter(product=self.object)
        if reviews:
            sum = 0
            for review in reviews:
                sum+=int(review.rating)
            rating = float(sum) * 5 / (5*len(reviews))
            self.object.rating = rating
        # return all his reviews
        context['reviews'] = reviews
        return context

class ProductCreateView(LoginRequiredMixin, IsOwnerMixin, CreateView):
    model = Product
    form_class = ProductModelForm
    pk_url_kwarg = 'uuid'
    slug_or_pk_shop = 'shop_slug'

    def get_success_url(self):
        return reverse_lazy('product:detail', args=(self.object.pk,))

    def form_valid(self, form):
        form_serialized = form.save(commit=False)
        form_serialized.shop = self.shop
        form_serialized.save()
        return super(ProductCreateView, self).form_valid(form)

class ProductUpdateView(LoginRequiredMixin, IsOwnerMixin, UpdateView):
    model = Product
    form_class = ProductModelForm
    pk_url_kwarg = 'uuid'
    slug_or_pk_shop = 'shop_slug'

    def get_success_url(self):
        return reverse_lazy('product:detail', args=(self.object.pk,))

class ProductDeleteView(LoginRequiredMixin, IsOwnerMixin, DeleteView):
    model = Product
    pk_url_kwarg = 'uuid'
    slug_or_pk_shop = 'shop_slug'

    def get_success_url(self):
        return reverse_lazy('shop:detail', args=(self.object.shop.slug,))

templates/product/product_confirm_delete.html
{% extends "blank.html" %}

{% block title %}
  {{ object.name }} - delete
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col s12 m6 push-m3">
      <form method="post">
        {% csrf_token %}
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{ object.name|title }}</span>
              <p>{{ object.description }}</p>
            </div>
            <div class="card-action">
              <a href="javascript:window.history.back()" class="waves-effect waves-light btn grey">Back</a>
              <button type="submit" class="waves-effect waves-light btn red">Delete Product</button>
            </div>
          </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/product/product_detail.html
{% extends "base.html" %}

{% block title %}
  {{ object.name }}
{% endblock %}

{% block main %}
  <div class="row container product_detail" data-id="{{ object.id }}">
    <div class="col s12 m6 product_left">
      <div class="row">
        <img src="{{ object.photo.url }}" class="photo" width="450" height="450" />
      </div>
      <div class="row">
        {% for cat in object.categories.all %}
          <div class="chip">
            <a href="{{ cat.slug }}">{{ cat.title }}</a>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="col s12 m6 product_right">
      <div class="row">
        <h3 class="title">{{ object.name|title }}</h3>
        <p>{{ object.description }}</p>
        <span class="rating left" data-product="{{ object.id }}" title="{{ object.rating }}">
          {% with object.rating as rating %}
            {% include "components/stars.html" %}
          {% endwith %}
        </span>
      </div>
      <div class="row">
        <h4 class="price">
          {% if object.new_price %}
            <span class="price-old">{{ object.price }}</span> / ${{ object.new_price }}
          {% else %}
            {{ object.price }}
          {% endif %}
          <br>
        </h4>
        {% if object.new_price %}
          <p>
            Discount {{ object.discount }}%
          </p>
        {% endif %}
      </div>
      <div class="row">
        <div class="col s12 m6">
          <div class="row">
            <input type="number" class="quantity" min="1" max="{{ product.quantity }}" value="1" />
            {% if object.id in shopping_cart %}
              <a href="#!"
                class="waves-effect waves-light btn red add_or_remove_product_cart"
                data-action="remove">
                <i class="material-icons left">remove_shopping_cart</i>
                <span>remove from cart</span>
              </a>
            {% else %}
              <a href="#!"
                class="waves-effect waves-light btn orange add_or_remove_product_cart"
                data-action="add">
                <i class="material-icons left">add_shopping_cart</i>
                <span>add to cart</span>
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% if request.user == object.shop.owner %}
      <div class="fixed-action-btn horizontal">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">mode_edit</i>
        </a>
        <ul>
          <li><a href="{% url 'product:edit' object.shop.slug object.pk %}" class="btn-floating orange"><i class="material-icons">mode_edit</i></a></li>
          <li><a href="{% url 'product:delete' object.shop.slug object.pk %}" class="btn-floating red"><i class="material-icons">delete</i></a></li>
        </ul>
      </div>
    {% endif %}
  </div>
  <div class="container white row">
    <h4>reviews</h4>
    <div id="reviews">
      {% for review in reviews %}
        {% include "components/card_comment.html" %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/product/product_form.html
{% extends "base.html" %}

{% block title %}
  {% if object %}
    {{ object.name }} - edit
  {% else %}
    New Product
  {% endif %}
{% endblock %}

{% block main %}
  <div class="row container">
    <div class="col s12 m6 push-m3">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.label == 'Categories' %}
            <div class="input-field row">
              {{ field }}
              <label>{{ field.label }}</label>
            </div>
          {% elif field.label == 'Photo' %}
            <div class="row file-field input-field">
              <div class="btn">
                <span>{{ field.label }}</span>
                {{ field }}
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>
          {% else %}
            <div class="row input-field">
              {{ field }}
              <label for="">{{ field.label }}</label>
            </div>
          {% endif %}
        {% endfor %}
        <div class="row">
          <button class="btn waves-effect waves-light right" type="submit" name="action">
            {% if object %}Save Change{% else %}Submit{% endif %}
            <i class="material-icons right">send</i>
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/product/product_list.html
{% extends "base.html" %}

{% block title %}
  Home
{% endblock %}

{% block main %}
  <div class="row container">
    <div class="col s12 m4 hide-on-small-only white">
      {% include "components/cat_menu.html" %}
    </div>
    <div class="col s12 m8 white">
      {% include "components/search_form.html" %}
      <div class="row list_products">
        {% if object_list %}
          {% for product in object_list %}
            {% include "components/card_product.html" %}
          {% endfor %}
        {% else %}
          <h5 class="no_found_text">Items Not Found</h5>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}