auth/urls.py
from django.conf.urls import url
from auth import views

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

review/urls.py
from django.conf.urls import url

from review import views

urlpatterns = [
    url(r'^$', views.ReviewView.as_view(), name='new'),
]

shop/urls.py
from django.conf.urls import url

from shop import views

urlpatterns = [
    url(r'^create/$', views.ShopCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ShopDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.ShopUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.ShopDeleteView.as_view(), name='delete'),
]

stores_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^', include('product.urls', namespace='product')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^@(?P<slug>[\w-]+)/$', views.ProfileDetailView.as_view(), name='profile'),
]

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from users.models import User
import uuid

# funcion para almacenamiento de imagenes
def content_file_name(instance, filename):
    return '/'.join(['shops', str(instance.slug), filename])

# Create your models here.
class Shop(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=60)
    description = models.TextField()
    logo = models.ImageField(upload_to=content_file_name)
    cover_image = models.ImageField(blank=True, upload_to=content_file_name)
    slug = models.SlugField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def logo_img(self):
        return self.logo.url

    def save(self, *args, **kwargs):
		if self.id:
			self.slug = slugify(self.name)
			super(Shop, self).save(*args, **kwargs)
		else:
			super(Shop, self).save(*args, **kwargs)

shop/forms.py
from django import forms

from shop.models import Shop

class ShopModelForm(forms.ModelForm):
    # description = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

    class Meta:
        model = Shop
        fields = ('name', 'description', 'logo', 'cover_image',)
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'})
        }

shop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from shop.models import Shop
from shop.forms import ShopModelForm

from product.models import Product
from review.models import Review
from product.mixins import IsOwnerMixin

# Create your views here.

class ShopDetailView(DetailView):
    model = Shop

    def get_context_data(self, **kwargs):
        context = super(ShopDetailView, self).get_context_data(**kwargs)
        self.product_list = Product.objects.filter(shop=self.object)
        for index, product in enumerate(self.product_list):
            if product.discount:
                self.product_list[index].new_price = (float(product.price)
                    - ((product.discount * float(product.price)) / 100))
            # add rating to products
            reviews = Review.objects.filter(product=product).values_list('rating', flat=True)
            if reviews:
                sum = 0
                for review in reviews:
                    sum+=int(review)
                rating = float(sum) * 5 / (5*len(reviews))
                self.product_list[index].rating = rating
        context['products'] = self.product_list
        return context

class ShopCreateView(LoginRequiredMixin, CreateView):
    model = Shop
    form_class = ShopModelForm

    def form_valid(self, form):
        __object = form.save(commit=False)
        __object.owner = self.request.user
        self.object = __object.save()
        return super(ShopCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('shop:detail', args=(self.object.slug,))


class ShopUpdateView(LoginRequiredMixin, IsOwnerMixin, UpdateView):
    model = Shop
    form_class = ShopModelForm

    def get_success_url(self):
        return reverse_lazy('shop:detail', args=(self.object.slug,))

class ShopDeleteView(LoginRequiredMixin, IsOwnerMixin, DeleteView):
    model = Shop

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.request.user.username,))

templates/shop/shop_confirm_delete.html
{% extends "blank.html" %}

{% block title %}
  Delete - {{ object.name|title }}
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col s12 m6 push-m3">
      <form method="post">
        {% csrf_token %}
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{ object.name|title }}</span>
              <p>{{ object.description }}</p>
            </div>
            <div class="card-action">
              <a href="javascript:window.history.back()" class="waves-effect waves-light btn grey">Back To The Shop</a>
              <button type="submit" class="waves-effect waves-light btn red">Delete Shop</button>
            </div>
          </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/shop/shop_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}
  {{ object.name|title }}
{% endblock %}

{% block main %}
  <div class="row shop container">
    <div class="col s12 m12">
      <div class="row margin-top">
        <div class="col s12 m3 center">
          <div class="shop_logo">
            {% if object.logo %}
              <img src="{{ object.logo.url }}" width="320" height="320" class="responsive-img" />
            {% endif %}
          </div>
          <h5>{{ object.name|title }}</h5>
          <a href="{% url 'users:profile' object.owner %}">@{{ object.owner }}</a>
          <div class="row"></div>
          {% if request.user == object.owner %}
          <a href="{% url 'product:new' object.slug %}" class="waves-effect waves-light btn hide-on-med-and-down"><i class="material-icons left">add</i>publish</a>
            <a href="{% url 'product:new' object.slug %}" class="waves-effect waves-light btn hide-on-large-only">publish</a>
            <div class="fixed-action-btn horizontal">
              <a class="btn-floating btn-large">
                <i class="large material-icons">mode_edit</i>
              </a>
              <ul>
                <li><a class="btn-floating blue" href="{% url 'shop:edit' object.slug %}"><i class="material-icons">mode_edit</i></a></li>
                <li><a class="btn-floating red" href="{% url 'shop:delete' object.slug %}"><i class="material-icons">delete</i></a></li>
              </ul>
            </div>
          {% endif %}
        </div>
        <div class="col m9 center hide-on-small-only">
          <div class="row cover_image">
            {% if object.cover_image %}
              {% thumbnail object.cover_image "800x380" crop="top" as img %}
                  <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}" class="responsive-img">
              {% endthumbnail %}
            {% endif %}
          </div>
          <div class="row">
            <p>
              {{ object.description }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row container">
    {% for product in products %}
      {% include "components/card_product.html" %}
    {% endfor %}
  </div>
{% endblock %}

templates/shop/shop_form.html
{% extends "base.html" %}

{% block title %}
  {% if not object %}
    New Shop
  {% else %}
    {{ object.name|title }} - edit
  {% endif %}
{% endblock %}

{% block main %}
  <div class="row">
    <div class="col s12 m6 push-m3">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
          {% if field.label == 'Description' %}
            <div class="row">
              <div class="input-field col s12">
                {{ field }}
                <label for="">{{ field.label }}</label>
              </div>
            </div>
          {% elif field.label == 'Logo' or field.label == 'Cover image' %}
            <div class="file-field input-field">
              <div class="btn">
                <span>{{ field.label }}</span>
                {{ field }}
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
              </div>
            </div>
          {% else %}
            <div class="row">
              <div class="input-field col s12">
                {{ field }}
                <label for="">{{ field.label }}</label>
              </div>
            </div>
          {% endif %}
        {% endfor %}
        <div class="row">
          <button class="btn waves-effect waves-light right" type="submit" name="action">
            {% if not object %}Create{% else %}Save Changes{% endif %}
            <i class="material-icons right">save</i>
          </button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}