auth/urls.py
from django.conf.urls import url
from auth import views

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

product/urls.py
from django.conf.urls import url
from product import views

urlpatterns = [
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^(?P<uuid>[\w-]+)/detail/$',
        views.ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<shop_slug>[\w-]+)/new/$',
        views.ProductCreateView.as_view(), name='new'),
    url(r'^(?P<shop_slug>[\w-]+)/(?P<uuid>[\w-]+)/edit/$',
        views.ProductUpdateView.as_view(), name='edit'),
    url(r'^(?P<shop_slug>[\w-]+)/(?P<uuid>[\w-]+)/delete/$',
        views.ProductDeleteView.as_view(), name='delete'),
]

stores_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^', include('product.urls', namespace='product')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^@(?P<slug>[\w-]+)/$', views.ProfileDetailView.as_view(), name='profile'),
]

templates/base.html
{% extends "blank.html" %}

{% load static %}

{% block body %}
  <header class="header">
    <div class="topBar">
      <div class="row container">
        <div class="col s6">
          <ul class="social">
            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
          </ul>
        </div>
        <div class="col s6">
          <ul class="social right">
            <li><a href="#"><i class="fa fa-search"></i></a></li>
            <li>|</li>
            {% if not request.user.is_authenticated %}
              <li><a href="{% url 'auth:signin' %}">Signin</a></li>
              <li>or</li>
              <li><a href="{% url 'auth:signup' %}">Signup</a></li>
            {% else %}
              <li><a href="{% url 'users:profile' request.user.username %}">@{{ request.user.username }}</a></li>
              <li><a href="#!" class="orange" id="user_money"><strong>${{ request.user.money }}</strong></a></li>
              <li><a href="{% url 'auth:logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="nav">
      <div class="row container">
        <div class="col s12 m2 content_logo">
          <h2 class="logo">Stores-<span>Center</span></h2>
        </div>
        <div class="col m10 hide-on-small-only nav_bar">
          <nav>
            <ul class="right">
              {% for item in menu %}
                <li><a href="{{ item.url }}" {% if item.active %}class="active"{% endif %}>{{ item.name }}</a></li>
              {% endfor %}
              <li>
                <a href="{% url 'shopping_cart:list' %}" class="card">
                  <i class="material-icons">shopping_cart</i>
                  <span class="new badge blue" data-badge-caption="Products" id="cart_count">{{ shopping_cart.count }}</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <main class="white">
    {% block main %}

    {% endblock %}
  </main>
{% endblock %}

templates/blank.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/app.css" %}" />
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      rel="stylesheet"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous">
  </head>
  <body>
    {% block body %}

    {% endblock %}
    {% block javascript %}{% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "js/app.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
  </body>
</html>