auth/urls.py
from django.conf.urls import url
from auth import views

urlpatterns = [
    url(r'^signin/$', views.SigninView.as_view(), name='signin'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

shop/urls.py
from django.conf.urls import url

from shop import views

urlpatterns = [
    url(r'^create/$', views.ShopCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.ShopDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.ShopUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.ShopDeleteView.as_view(), name='delete'),
]

stores_center/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^', include('product.urls', namespace='product')),
    url(r'^review/', include('review.urls', namespace='review')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^@(?P<slug>[\w-]+)/$', views.ProfileDetailView.as_view(), name='profile'),
]

shop/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from users.models import User
import uuid

# funcion para almacenamiento de imagenes
def content_file_name(instance, filename):
    return '/'.join(['shops', str(instance.slug), filename])

# Create your models here.
class Shop(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=60)
    description = models.TextField()
    logo = models.ImageField(upload_to=content_file_name)
    cover_image = models.ImageField(blank=True, upload_to=content_file_name)
    slug = models.SlugField(editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def logo_img(self):
        return self.logo.url

    def save(self, *args, **kwargs):
		if self.id:
			self.slug = slugify(self.name)
			super(Shop, self).save(*args, **kwargs)
		else:
			super(Shop, self).save(*args, **kwargs)

shop/forms.py
from django import forms

from shop.models import Shop

class ShopModelForm(forms.ModelForm):
    # description = forms.CharField(widget=forms.Textarea(attrs={'class': 'materialize-textarea'}))

    class Meta:
        model = Shop
        fields = ('name', 'description', 'logo', 'cover_image',)
        widgets = {
            'description': forms.Textarea(attrs={'class': 'materialize-textarea'})
        }

shop/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from shop.models import Shop
from shop.forms import ShopModelForm

from product.models import Product
from review.models import Review
from product.mixins import IsOwnerMixin

# Create your views here.

class ShopDetailView(DetailView):
    model = Shop

    def get_context_data(self, **kwargs):
        context = super(ShopDetailView, self).get_context_data(**kwargs)
        self.product_list = Product.objects.filter(shop=self.object)
        for index, product in enumerate(self.product_list):
            if product.discount:
                self.product_list[index].new_price = (float(product.price)
                    - ((product.discount * float(product.price)) / 100))
            # add rating to products
            reviews = Review.objects.filter(product=product).values_list('rating', flat=True)
            if reviews:
                sum = 0
                for review in reviews:
                    sum+=int(review)
                rating = float(sum) * 5 / (5*len(reviews))
                self.product_list[index].rating = rating
        context['products'] = self.product_list
        return context

class ShopCreateView(LoginRequiredMixin, CreateView):
    model = Shop
    form_class = ShopModelForm

    def form_valid(self, form):
        __object = form.save(commit=False)
        __object.owner = self.request.user
        self.object = __object.save()
        return super(ShopCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('shop:detail', args=(self.object.slug,))


class ShopUpdateView(LoginRequiredMixin, IsOwnerMixin, UpdateView):
    model = Shop
    form_class = ShopModelForm

    def get_success_url(self):
        return reverse_lazy('shop:detail', args=(self.object.slug,))

class ShopDeleteView(LoginRequiredMixin, IsOwnerMixin, DeleteView):
    model = Shop

    def get_success_url(self):
        return reverse_lazy('users:profile', args=(self.request.user.username,))

templates/components/card_comment.html
<div class="card horizontal card_comment" data-user="{{ review.user.username }}">
  <div class="card-stacked">
    <div class="card-content">
        <a
          href="{% url 'users:profile' review.user.username %}"
          class="username">@{{ review.user.username }}</a>
      <p>{{ review.comment }}</p>
    </div>
    <div class="card-action">
      <span class="left" data-product="{{ review.product.id }}" title="{{ review.rating }}">
        {% with review.rating as rating %}
          {% include "components/stars.html" %}
        {% endwith %}
      </span>
    </div>
  </div>
</div>

templates/components/card_product.html
{% load thumbnail %}

<div class="card horizontal product" data-id="{{ product.id }}">
  <div class="card-image">
    {% thumbnail product.photo "120x190" crop="center" as img %}
        <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}">
    {% endthumbnail %}
  </div>
  <div class="card-stacked">
    <div class="card-content">
      <h6>
        <a href="{% url 'product:detail' product.pk %}" class="title">
          {{ product.name|title }}
        </a>
      </h6>
      {% if product.new_price %}
        <a href="#" class="price-old">{{ product.price }}</a>
        <a href="#" class="price">${{ product.new_price }}</a>
      {% else %}
        <a href="#" class="price">{{ product.price }}</a>
      {% endif %}
    </div>
    <div class="card-action">
      <span class="rating left" data-product="{{ product.id }}" title="{{product.rating}}">
        {% with product.rating as rating %}
          {% include "components/stars.html" %}
        {% endwith %}
      </span>
      {% if product.id in shopping_cart %}
        <a href="#"
          class="btn btn-floating red right add_or_remove_product_cart"
          data-action="remove">
          <i class="material-icons">remove_shopping_cart</i>
        </a>
      {% else %}
        <a href="#"
          class="btn btn-floating orange right add_or_remove_product_cart"
          data-action="add">
          <i class="material-icons">add_shopping_cart</i>
        </a>
      {% endif %}
    </div>
  </div>
</div>

templates/components/cat_menu.html
<div class="menu_cat">
    <div class="collection">
      <a href="#" class="collection-item header">Categories</a>
      {% if not categories %}
        <h6 class="no_found_text">Categories Not Found</h6>
      {% endif %}
      {% for cat in categories %}
        <a href="?category={{ cat.slug }}"
          {% if cat.active %}
            class="collection-item active"
          {% else %}
            class="collection-item"
          {% endif %}>{{ cat.name }}</a>
      {% endfor %}
    </div>
</div>

templates/components/item_cart.html
{% load thumbnail %}

{% with item.product as product %}
<div class="card horizontal product" data-id="{{ product.id }}">
  <div class="card-image">
    {% thumbnail product.photo "120x190" crop="center" as img %}
        <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}">
    {% endthumbnail %}
  </div>
  <div class="card-stacked">
    <div class="card-content">
      <h6>
        <a href="{% url 'product:detail' product.pk %}" class="title">
          {{ product.name|title }}
        </a>
      </h6>
      {% if product.new_price %}
        <a href="#" class="price-old">{{ product.price }}</a>
        <a href="#" class="price">${{ product.new_price }}</a>
      {% else %}
        <a href="#" class="price">{{ product.price }}</a>
      {% endif %}
    </div>
    <div class="card-action">
      <span class="color-green left">
        Quantity: <strong>{{ item.quantity }}</strong>
      </span>
      <span class="right">
        {% if request.user == item.user %}
          <a href="#" class="btn btn-floating red add_or_remove_product_cart" data-action="remove" title="remove to cart">
            <i class="material-icons">remove_shopping_cart</i>
          </a>
          <a href="#" class="btn btn-floating orange shop_now" title="buy now">
            <i class="material-icons">shop</i>
          </a>
        {% else %}
          <a href="#" class="btn btn-floating orange add_or_remove_product_cart" data-action="add" title="add to cart">
            <i class="material-icons">add_shopping_cart</i>
          </a>
        {% endif %}
      </span>
    </div>
  </div>
</div>
{% endwith %}

templates/components/search_form.html
<div class="row">
  <form id="search_form" method="get">
    <div class="input-field col s4">
      <div class="row">
        <select class="browser-default" name="category">
          <option value="" disabled selected>Category</option>
          {% for cat in categories %}
            <option value="{{ cat.slug }}" {% if cat.active %} selected {% endif %}>{{ cat.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="col s8">
      <div class="row">
        <div class="input-field col s9">
          <div class="row">
            <input placeholder="Search" id="search" name="search" type="text" value="{{ request.GET.search }}" class="validate">
          </div>
        </div>
        <div class="input-field col s3">
          <div class="row">
            <button class="btn waves-effect waves-light btn-flat btn-large" type="submit">
              <i class="material-icons">search</i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>

templates/components/shop.html
{% load thumbnail %}

<div class="card horizontal">
  <div class="card-image">
    {% thumbnail shop.logo "120x190" crop="center" as img %}
      <img src="{{ img.url }}" width="{{ img.width }}" height="{{ img.height }}">
    {% endthumbnail %}
  </div>
  <div class="card-stacked">
    <div class="card-content">
      <h5><a href="{% url 'shop:detail' shop.slug %}" class="title">{{ shop.name|title }}</a></h5>
      <p>
        {{ shop.description|truncatechars:140 }}
      </p>
    </div>
    <div class="card-action">
      <a href="#">Offertas</a>
    </div>
  </div>
</div>

templates/components/stars.html
{% load convert_to_rank %}

{% for i in 5|convert_to_rank %}
  {% if rating < i or not rating %}
    <i class="fa fa-star-o" aria-hidden="true" data-index="{{i}}"></i>
  {% else %}
    <i class="fa fa-star" aria-hidden="true" data-index="{{i}}"></i>
  {% endif %}
{% endfor %}